In [2]:
# importing the modules
import pandas as pd
import numpy as np
import os.path

# creating a DataFrame
ODI_runs = {'name': ['Tendulkar', 'Sangakkara', 'Ponting',
                     'Jayasurya', 'Jayawardene', 'Kohli',
                     'Haq', 'Kallis', 'Ganguly', 'Dravid'],
            'runs': [18426, 14234, 13704, 13430, 12650,
                     11867, 11739, 11579, 11363, 10889],
            'status': [30, 130, 131, 31, 130, 130, 131, 131, 131, 130]}
df = pd.DataFrame(ODI_runs)

print(df)
# # displaying the original DataFrame
# print("Original DataFrame :")
# print(df)

# # dropping the 0th and the 1st index
# df = df.drop([2, 3])

# # displaying the altered DataFrame
# print("DataFrame after removing the 0th and 1st row")
# print(df)

# # resetting the DataFrame index
# df = df.reset_index()

# # displaying the DataFrame with new index
# print("Dataframe after resetting the index")
# print(df)

# df = df.drop(['index'], axis=1)
# print(df)

# print(df.loc[df.shape[0]-1])

# if not os.path.isfile('Pulling_3bs'+'/'+'16''.txt'):
    # print("Ciao")



          name   runs  status
0    Tendulkar  18426      30
1   Sangakkara  14234     130
2      Ponting  13704     131
3    Jayasurya  13430      31
4  Jayawardene  12650     130
5        Kohli  11867     130
6          Haq  11739     131
7       Kallis  11579     131
8      Ganguly  11363     131
9       Dravid  10889     130


In [3]:
df.loc[df.shape[0]-1].at['name']

'Dravid'

In [4]:
df.columns

Index(['name', 'runs', 'status'], dtype='object')

In [5]:
df_empty = pd.DataFrame(columns = df.columns)
df_empty

Empty DataFrame
Columns: [name, runs, status]
Index: []

In [6]:
df_empty2 = df_empty.copy()
df_empty2

Empty DataFrame
Columns: [name, runs, status]
Index: []

In [7]:
df.loc[0].values

array(['Tendulkar', 18426, 30], dtype=object)

In [8]:
df_empty2 = df_empty2.append(df.loc[0], ignore_index=True)
df_empty2

name   runs status
0  Tendulkar  18426     30

In [9]:
df_empty2 = df_empty2.append(df.loc[2], ignore_index=True)
df_empty2

name   runs status
0  Tendulkar  18426     30
1    Ponting  13704    131

In [10]:
df

name   runs  status
0    Tendulkar  18426      30
1   Sangakkara  14234     130
2      Ponting  13704     131
3    Jayasurya  13430      31
4  Jayawardene  12650     130
5        Kohli  11867     130
6          Haq  11739     131
7       Kallis  11579     131
8      Ganguly  11363     131
9       Dravid  10889     130

In [11]:
df_empty3 = df_empty.copy()

In [12]:

df_empty2 = df_empty2.append(df_empty3, ignore_index=True)

In [13]:
df_empty2

name   runs status
0  Tendulkar  18426     30
1    Ponting  13704    131

In [14]:
# for i in range(df.shape[0]):
# df_empty = df.loc[df['status'] == 130]

# print(df_empty)
# print(df_empty.iloc[1].index)

lista = df.index[df['status'] == 130].tolist()
lista.append(0) # qui più chiaro più avanti per fare un loop completo
print(lista)
# print(df.loc[0])
# sub_lista = []
# while len(lista) != 0:
j = 0
# print(df.iloc[lista[0]])
df_empty = pd.DataFrame(columns = df.columns)
df_empty2 = df_empty.copy()
for i in range(len(lista)-1):
    if lista[i+1] - lista[i] == 1:
        # if df_empty2.empty:
        df_empty2 = df_empty2.append(df.loc[lista[i]], ignore_index=True)
            # print(df_empty2.index)
        # else:
        #     # TODO
        #     df_empty2 = pd.concat([df_empty2.to_frame(), df.loc[lista[i]].to_frame()], ignore_index=True)
        #     # print(df_empty2)
    else:
        # if df_empty2.empty:
            # print("si sono vuoto al giro ", i)
        df_empty2 = df_empty2.append(df.loc[lista[i]], ignore_index=True)
        # else:
        #     # TODO
        #     # print("no non sono vuoto al giro ", i)
        #     df_empty2 = pd.concat([df_empty2.to_frame(), df.loc[lista[i]].to_frame()], ignore_index=True)
        #     # df_empty2.rename(columns=df_empty2.index)
        #     print(df_empty2.index)
            # df_empty2 = df_empty2.iloc[0:, :]
        # df_empty = df.loc[lista[i]].copy()
        # df_empty2.to_frame()
        # df_empty2.reset_index() # MA FORSE TORNA UTILE
        # print(df_empty2)
        with open(os.path.join("Pulling_3bs", 'Prova'+str(j)+'.txt'), 'w') as outfile:
            df_empty2.to_string(outfile)
        j += 1
        df_empty2 = df_empty.iloc[0:0].copy()  # svuota il dataframe

# print(df)


[1, 4, 5, 9, 0]


In [15]:
df

name   runs  status
0    Tendulkar  18426      30
1   Sangakkara  14234     130
2      Ponting  13704     131
3    Jayasurya  13430      31
4  Jayawardene  12650     130
5        Kohli  11867     130
6          Haq  11739     131
7       Kallis  11579     131
8      Ganguly  11363     131
9       Dravid  10889     130

In [16]:
lista

[1, 4, 5, 9, 0]

In [17]:
import pandas as pd

data = []
data.append(pd.read_fwf('Pulling_3bs/16u86.txt'))
data_frame = pd.concat([j for j in data], ignore_index=True) # I add together all the datasets
data_frame

X_force  Z_force   lambda  Y_force    time(sec)
0      0.6030   0.6154  0.09550   1.7195  27044.99023
1      0.7217   0.5999  0.24770   1.6117  27044.99023
2      0.8159   0.5999  0.18655   1.6117  27044.99219
3     -0.3410   0.3853  0.02805   1.9046  27044.99219
4     -0.3672   0.3012 -0.15375   2.0208  27044.99414
...       ...      ...      ...      ...          ...
3153  -0.7232   0.3389  3.56390  12.3430  27048.27344
3154  -0.0601   0.2055  4.13800  12.3043  27048.27344
3155   0.1912   0.1359  3.78215  12.3245  27048.27539
3156   0.4495   0.1166  4.04705  12.2908  27048.27539
3157   0.0935   0.2055  3.03245  12.3985  27048.27734

[3158 rows x 5 columns]

In [18]:
data_frame.loc[0].at['time(sec)']

27044.99023

In [19]:
data_frame.loc[data_frame.shape[0]-1].at['time(sec)']

27048.277339999997

In [20]:
ODI_runs = {'name': ['Tendulkar', 'Sangakkara', 'Ponting',
					'Jayasurya', 'Jayawardene', 'Kohli',
					'Haq', 'Kallis', 'Ganguly'],
			'runs': [-18426, 14234, 13704, 13430, -12650,
					11867, 11739, -11579, 11363],
			'status': [30, 130, 131, 31, 130, 130, 131, 131, 131]}
df = pd.DataFrame(ODI_runs)


In [21]:
df

name   runs  status
0    Tendulkar -18426      30
1   Sangakkara  14234     130
2      Ponting  13704     131
3    Jayasurya  13430      31
4  Jayawardene -12650     130
5        Kohli  11867     130
6          Haq  11739     131
7       Kallis -11579     131
8      Ganguly  11363     131

In [22]:
ciao = np.zeros(5)
for i in range(ciao.size-1):
	ciao[i] = df['runs'].loc[i+1] - df['runs'].loc[i]
print(ciao)
res = np.where(ciao == ciao.min())
print(res)
df['runs'][res[0]*2-1].values[0]

[ 32660.   -530.   -274. -26080.      0.]
(array([3], dtype=int64),)


11867

In [23]:
df['runs'][res[0]*2-1].values[0]

11867

In [24]:
np.where(df['runs'].values == 11867)[0][0]

5

In [25]:
sub_row = df.loc[df.index[df['runs'] == 11867].tolist()]

In [26]:
sub_row

name   runs  status
5  Kohli  11867     130

In [27]:
df['runs'].loc[1:5]

1    14234
2    13704
3    13430
4   -12650
5    11867
Name: runs, dtype: int64

In [28]:
median = df['runs'].loc[1:5].median()

In [29]:
sub_row = df.loc[df.index[df['runs'] == median].tolist()]

In [30]:
df

name   runs  status
0    Tendulkar -18426      30
1   Sangakkara  14234     130
2      Ponting  13704     131
3    Jayasurya  13430      31
4  Jayawardene -12650     130
5        Kohli  11867     130
6          Haq  11739     131
7       Kallis -11579     131
8      Ganguly  11363     131

In [31]:
df_empty = pd.DataFrame(columns = df.columns)
for i in range(df.shape[0]-2):
    median = df['runs'].loc[i:i+2].median()
    sub_row = df.loc[df.index[df['runs'] == median].tolist()]
    df_empty = df_empty.append(sub_row, ignore_index=False)
df_empty = df_empty.reset_index()
df_empty = df_empty.drop(['index'], axis=1)

In [32]:
df_empty2 = df_empty[['runs', 'status']].copy()

In [33]:
df_empty2

runs status
0  13704    131
1  13704    131
2  13430     31
3  11867    130
4  11739    131
5  11739    131
6  11363    131

In [34]:
from scipy.signal import medfilt
y1 = medfilt(df['runs'], kernel_size=5)
y1

array([    0, 13430, 13430, 13430, 11867, 11739, 11363, 11363,     0],
      dtype=int64)

In [35]:
df_empty = pd.DataFrame(columns = df.columns)
for i in range(df.shape[0]-2):
    y1 = medfilt(df['runs'], kernel_size=3)
    sub_row = df.loc[df.index[df['runs'] == y1[i]].tolist()]
    df_empty = df_empty.append(sub_row, ignore_index=False)
df_empty = df_empty.reset_index()
df_empty = df_empty.drop(['index'], axis=1)

In [36]:
df['runs'].loc[0]

-18426

In [37]:
df_empty

name   runs status
0    Ponting  13704    131
1    Ponting  13704    131
2  Jayasurya  13430     31
3      Kohli  11867    130
4        Haq  11739    131
5        Haq  11739    131

In [38]:
def func(arr, i):
    j = [k for k in arr if k in range(i, i+5)]
    return j

In [39]:
df.loc[func(df.loc[1:3:2].index.to_list(), 2)]

name   runs  status
3  Jayasurya  13430      31

In [40]:
data = []
data.append(pd.read_fwf('Pulling_3bs/16u2.txt', colspecs = [(0, 9), (9, 17), (17, 28), (28, 37), (37, -1)]))
print(data)
# print(data)
data_frame = pd.DataFrame(columns = ['X_force', 'Z_force', 'lambda', 'Y_force', 'time(sec)'])
data_frame = pd.concat([j for j in data], ignore_index=True)

[      X_force  Z_force     lambda  Y_force    time(sec)
0     -0.0531   0.1127    4.42950   1.5915  26509.98438
1      0.4076   0.1823    4.06080   1.8541  26509.98438
2      0.2976   0.2287    3.07610   1.6269  26509.98438
3      0.2139   0.2287    2.98510   1.5511  26509.98633
4     -0.0531   0.3969    2.70625   1.5511  26509.98828
...       ...      ...        ...      ...          ...
3283  -0.2206  -0.0033  206.92460  12.2235  26513.41406
3284  -0.1997   0.0460  206.67035  12.1612  26513.41406
3285   0.2453   0.1852  206.49880  12.2066  26513.41602
3286  -0.3148   0.3041  206.69895  12.0955  26513.41797
3287  -0.5452   0.2403  206.70375  12.2167  26513.41990

[3288 rows x 5 columns]]


In [41]:
data_frame

X_force  Z_force     lambda  Y_force    time(sec)
0     -0.0531   0.1127    4.42950   1.5915  26509.98438
1      0.4076   0.1823    4.06080   1.8541  26509.98438
2      0.2976   0.2287    3.07610   1.6269  26509.98438
3      0.2139   0.2287    2.98510   1.5511  26509.98633
4     -0.0531   0.3969    2.70625   1.5511  26509.98828
...       ...      ...        ...      ...          ...
3283  -0.2206  -0.0033  206.92460  12.2235  26513.41406
3284  -0.1997   0.0460  206.67035  12.1612  26513.41406
3285   0.2453   0.1852  206.49880  12.2066  26513.41602
3286  -0.3148   0.3041  206.69895  12.0955  26513.41797
3287  -0.5452   0.2403  206.70375  12.2167  26513.41990

[3288 rows x 5 columns]

In [48]:
df = pd.DataFrame({'a': [1, 2, 3, 4, 5, 6],
                   'b': [1, 1, 2, 3, 5, 8],
                   'c': [1, 4, 5, 6, 7, 10]})

In [49]:
df

a  b   c
0  1  1   1
1  2  1   4
2  3  2   5
3  4  3   6
4  5  5   7
5  6  8  10

In [58]:
lista = df.index[df['c'].diff() > 1].tolist()

In [59]:
lista

[1, 5]

In [61]:
df2 = pd.DataFrame(columns = df.columns)
for i in lista:
    df2 = df2.append(df.loc[i], ignore_index=True)
df2

a  b   c
0  2  1   4
1  6  8  10

In [47]:
df2

a  b  c
3  4  3  6

In [1]:
import numpy as np

In [7]:
def mypolyval(ciao, x):
    _p = list(ciao)
    res = _p.pop(0)
    while _p:
        res = res*x + _p.pop(0)
    return res
vpolyval = np.vectorize(mypolyval, excluded=['ciao'])
vpolyval(ciao=[1, 2, 3], x=[0, 1])

array([3, 6])