In [3]:
# importing the modules
import pandas as pd
import numpy as np
import os.path

# creating a DataFrame
ODI_runs = {'name': ['Tendulkar', 'Sangakkara', 'Ponting',
                     'Jayasurya', 'Jayawardene', 'Kohli',
                     'Haq', 'Kallis', 'Ganguly', 'Dravid'],
            'runs': [18426, 14234, 13704, 13430, 12650,
                     11867, 11739, 11579, 11363, 10889],
            'status': [30, 130, 131, 31, 130, 130, 131, 131, 131, 130]}
df = pd.DataFrame(ODI_runs)

print(df)
# # displaying the original DataFrame
# print("Original DataFrame :")
# print(df)

# # dropping the 0th and the 1st index
# df = df.drop([2, 3])

# # displaying the altered DataFrame
# print("DataFrame after removing the 0th and 1st row")
# print(df)

# # resetting the DataFrame index
# df = df.reset_index()

# # displaying the DataFrame with new index
# print("Dataframe after resetting the index")
# print(df)

# df = df.drop(['index'], axis=1)
# print(df)

# print(df.loc[df.shape[0]-1])

# if not os.path.isfile('Pulling_3bs'+'/'+'16''.txt'):
    # print("Ciao")



          name   runs  status
0    Tendulkar  18426      30
1   Sangakkara  14234     130
2      Ponting  13704     131
3    Jayasurya  13430      31
4  Jayawardene  12650     130
5        Kohli  11867     130
6          Haq  11739     131
7       Kallis  11579     131
8      Ganguly  11363     131
9       Dravid  10889     130


In [182]:
df.loc[df.shape[0]-1].at['name']

'Dravid'

In [167]:
df.columns

Index(['name', 'runs', 'status'], dtype='object')

In [168]:
df_empty = pd.DataFrame(columns = df.columns)
df_empty

Empty DataFrame
Columns: [name, runs, status]
Index: []

In [169]:
df_empty2 = df_empty.copy()
df_empty2

Empty DataFrame
Columns: [name, runs, status]
Index: []

In [170]:
df.loc[0].values

array(['Tendulkar', 18426, 30], dtype=object)

In [171]:
df_empty2 = df_empty2.append(df.loc[0], ignore_index=True)
df_empty2

name   runs status
0  Tendulkar  18426     30

In [172]:
df_empty2 = df_empty2.append(df.loc[2], ignore_index=True)
df_empty2

name   runs status
0  Tendulkar  18426     30
1    Ponting  13704    131

In [173]:
df

name   runs  status
0    Tendulkar  18426      30
1   Sangakkara  14234     130
2      Ponting  13704     131
3    Jayasurya  13430      31
4  Jayawardene  12650     130
5        Kohli  11867     130
6          Haq  11739     131
7       Kallis  11579     131
8      Ganguly  11363     131
9       Dravid  10889     130

In [164]:
df_empty3 = df_empty.copy()

In [165]:

df_empty2 = df_empty2.append(df_empty3, ignore_index=True)

In [166]:
df_empty2

name   runs status
0  Tendulkar  18426     30

In [177]:
# for i in range(df.shape[0]):
# df_empty = df.loc[df['status'] == 130]

# print(df_empty)
# print(df_empty.iloc[1].index)

lista = df.index[df['status'] == 130].tolist()
lista.append(0) # qui più chiaro più avanti per fare un loop completo
print(lista)
# print(df.loc[0])
# sub_lista = []
# while len(lista) != 0:
j = 0
# print(df.iloc[lista[0]])
df_empty = pd.DataFrame(columns = df.columns)
df_empty2 = df_empty.copy()
for i in range(len(lista)-1):
    if lista[i+1] - lista[i] == 1:
        # if df_empty2.empty:
        df_empty2 = df_empty2.append(df.loc[lista[i]], ignore_index=True)
            # print(df_empty2.index)
        # else:
        #     # TODO
        #     df_empty2 = pd.concat([df_empty2.to_frame(), df.loc[lista[i]].to_frame()], ignore_index=True)
        #     # print(df_empty2)
    else:
        # if df_empty2.empty:
            # print("si sono vuoto al giro ", i)
        df_empty2 = df_empty2.append(df.loc[lista[i]], ignore_index=True)
        # else:
        #     # TODO
        #     # print("no non sono vuoto al giro ", i)
        #     df_empty2 = pd.concat([df_empty2.to_frame(), df.loc[lista[i]].to_frame()], ignore_index=True)
        #     # df_empty2.rename(columns=df_empty2.index)
        #     print(df_empty2.index)
            # df_empty2 = df_empty2.iloc[0:, :]
        # df_empty = df.loc[lista[i]].copy()
        # df_empty2.to_frame()
        # df_empty2.reset_index() # MA FORSE TORNA UTILE
        # print(df_empty2)
        with open(os.path.join("Pulling_3bs", 'Prova'+str(j)+'.txt'), 'w') as outfile:
            df_empty2.to_string(outfile)
        j += 1
        df_empty2 = df_empty.iloc[0:0].copy()  # svuota il dataframe

# print(df)


[1, 4, 5, 9, 0]


In [175]:
df

name   runs  status
0    Tendulkar  18426      30
1   Sangakkara  14234     130
2      Ponting  13704     131
3    Jayasurya  13430      31
4  Jayawardene  12650     130
5        Kohli  11867     130
6          Haq  11739     131
7       Kallis  11579     131
8      Ganguly  11363     131
9       Dravid  10889     130

In [176]:
lista

[1, 4, 5, 9, 0]

In [205]:
import pandas as pd

data = []
data.append(pd.read_fwf('Pulling_3bs/16u86.txt'))
data_frame = pd.concat([j for j in data], ignore_index=True) # I add together all the datasets
data_frame

CycleCount  A_PsdX  A_PsdY  A_PsdSum  A_LeverX  A_LeverY  A_LeverSum  \
0         561330  -19.67  -72.00   8136.33    889.33   -113.67    20100.00   
1         561331  -17.00  -70.00   8137.00    891.00   -113.00    20101.00   
2         561332  -16.50  -70.50   8137.00    890.00   -114.50    20102.50   
3         561333  -41.25  -77.75   8143.25    889.50   -114.25    20103.75   
4         561334  -43.00  -81.00   8145.75    889.50   -114.50    20102.00   
...          ...     ...     ...       ...       ...       ...         ...   
3153      564607  -45.25  325.25   8167.00    931.75    216.00    20109.00   
3154      564608  -35.33  330.00   8171.67    931.67    216.67    20105.00   
3155      564609  -32.33  333.00   8173.67    932.33    216.67    20109.00   
3156      564610  -26.67  332.33   8174.67    932.00    217.67    20113.33   
3157      564611  -33.00  331.00   8170.00    932.00    215.00    20112.00   

      B_PsdX  B_PsdY  B_PsdSum  ...  A_dist-X  A_dist-Y  B_dist-X  B_dist-Y  \
0     -23.00  -72.33  10539.00  ...  630.8957  -86.2905  184.3088   86.4815   
1     -20.00  -69.00  10535.00  ...  632.0466  -85.7802  184.3526   86.2756   
2     -16.00  -68.50  10534.50  ...  631.2901  -86.9124  183.4385   87.2855   
3     -46.50  -75.75  10541.75  ...  630.8964  -86.7172  183.8801   86.7733   
4     -46.00  -78.25  10540.75  ...  630.9512  -86.9146  184.1861   86.6071   
...      ...     ...       ...  ...       ...       ...       ...       ...   
3153  -60.75  345.00  10615.25  ...  660.6904  163.9039  162.8256  243.2239   
3154  -39.00  338.33  10605.67  ...  660.7628  164.4425  163.0029  243.8335   
3155  -30.00  336.33  10598.33  ...  661.1039  164.4098  162.8055  243.1545   
3156  -23.33  335.33  10595.33  ...  660.7253  165.1330  162.8282  242.9611   
3157  -34.00  342.00  10601.00  ...  660.7690  163.1208  163.0166  242.9441   

      Motor_X  Motor_Y  Motor_Z    time(sec)  Status   lambda  
0       76.66   264.16  -385.74  27044.99023   131.0  0.09550  
1       76.66   264.16  -385.74  27044.99023   131.0  0.24770  
2       76.66   264.16  -385.74  27044.99219   131.0  0.18655  
3       76.66   264.16  -385.74  27044.99219   131.0  0.02805  
4       76.66   264.16  -385.74  27044.99414   131.0 -0.15375  
...       ...      ...      ...          ...     ...      ...  
3153    76.66   264.16  -385.74  27048.27344   131.0  3.56390  
3154    76.66   264.16  -385.74  27048.27344   131.0  4.13800  
3155    76.66   264.16  -385.74  27048.27539   131.0  3.78215  
3156    76.66   264.16  -385.74  27048.27539   131.0  4.04705  
3157    76.66   264.16  -385.74  27048.27734   131.0  3.03245  

[3158 rows x 34 columns]

In [206]:
data_frame.loc[0].at['time(sec)']

27044.99023

In [209]:
data_frame.loc[data_frame.shape[0]-1].at['time(sec)']

27048.277339999997

In [2]:
ODI_runs = {'name': ['Tendulkar', 'Sangakkara', 'Ponting',
					'Jayasurya', 'Jayawardene', 'Kohli',
					'Haq', 'Kallis', 'Ganguly'],
			'runs': [-18426, 14234, 13704, 13430, -12650,
					11867, 11739, -11579, 11363],
			'status': [30, 130, 131, 31, 130, 130, 131, 131, 131]}
df = pd.DataFrame(ODI_runs)


NameError: name 'pd' is not defined

In [214]:
df

name   runs  status
0    Tendulkar -18426      30
1   Sangakkara  14234     130
2      Ponting  13704     131
3    Jayasurya  13430      31
4  Jayawardene -12650     130
5        Kohli  11867     130
6          Haq  11739     131
7       Kallis -11579     131
8      Ganguly  11363     131

In [220]:
ciao = np.zeros(5)
for i in range(ciao.size-1):
	ciao[i] = df['runs'].loc[i+1] - df['runs'].loc[i]
print(ciao)
res = np.where(ciao == ciao.min())
print(res)
df['runs'][res[0]*2-1].values[0]

[ 32660.   -530.   -274. -26080.      0.]
(array([3], dtype=int64),)


11867

In [222]:
df['runs'][res[0]*2-1].values[0]

11867

In [227]:
np.where(df['runs'].values == 11867)[0][0]

5

In [228]:
sub_row = df.loc[df.index[df['runs'] == 11867].tolist()]

In [229]:
sub_row

name   runs  status
5  Kohli  11867     130

In [234]:
df['runs'].loc[1:5]

1    14234
2    13704
3    13430
4   -12650
5    11867
Name: runs, dtype: int64

In [236]:
median = df['runs'].loc[1:5].median()

In [237]:
sub_row = df.loc[df.index[df['runs'] == median].tolist()]

In [241]:
df

name   runs  status
0    Tendulkar -18426      30
1   Sangakkara  14234     130
2      Ponting  13704     131
3    Jayasurya  13430      31
4  Jayawardene -12650     130
5        Kohli  11867     130
6          Haq  11739     131
7       Kallis -11579     131
8      Ganguly  11363     131

In [262]:
df_empty = pd.DataFrame(columns = df.columns)
for i in range(df.shape[0]-2):
    median = df['runs'].loc[i:i+2].median()
    sub_row = df.loc[df.index[df['runs'] == median].tolist()]
    df_empty = df_empty.append(sub_row, ignore_index=False)
df_empty = df_empty.reset_index()
df_empty = df_empty.drop(['index'], axis=1)

In [263]:
df_empty2 = df_empty[['runs', 'status']].copy()

In [264]:
df_empty2

runs status
0  13704    131
1  13704    131
2  13430     31
3  11867    130
4  11739    131
5  11739    131
6  11363    131

In [5]:
from scipy.signal import medfilt
y1 = medfilt(df['runs'], kernel_size=5)
y1

array([13704, 13704, 13704, 13430, 12650, 11867, 11739, 11579, 11363,
       10889], dtype=int64)

In [7]:
df_empty = pd.DataFrame(columns = df.columns)
for i in range(df.shape[0]-2):
    y1 = medfilt(df['runs'], kernel_size=3)
    sub_row = df.loc[df.index[df['runs'] == y1[i]].tolist()]
    df_empty = df_empty.append(sub_row, ignore_index=False)
df_empty = df_empty.reset_index()
df_empty = df_empty.drop(['index'], axis=1)

In [10]:
df['runs'].loc[0]

18426

In [11]:
df_empty

name   runs status
0   Sangakkara  14234    130
1   Sangakkara  14234    130
2      Ponting  13704    131
3    Jayasurya  13430     31
4  Jayawardene  12650    130
5        Kohli  11867    130
6          Haq  11739    131
7       Kallis  11579    131

In [25]:
def func(arr, i):
    j = [k for k in arr if k in range(i, i+5)]
    return j

In [26]:
df.loc[func(df.loc[1:3:2].index.to_list(), 2)]

name   runs  status
3  Jayasurya  13430      31